name: docker-publish-ghcr

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  packages: write

env:
  PLATFORMS: linux/amd64,linux/arm64
  BUILD_DIRS: |
    tutorials/test/
    tutorials/net/mtu/

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository..."
        uses: actions/checkout@v4
        with:
          path: code
          fetch-depth: 0
          fetch-tags: 1

      - name: "Set up Docker buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry (ghcr.io)"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push to ghcr"
        run: |
          cd code
          export TAG=latest

          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            export PUSH="--push"
          fi

          for dir in ${BUILD_DIRS}; do
            TAG="$(<${dir}/docker/tag):latest"
            echo "Building '${dir}/docker/Dockerfile' with tag '${TAG}'..."
            docker buildx build --platform ${PLATFORMS} ${PUSH} -f ${dir}/docker/Dockerfile ${dir} --tag ghcr.io/${GITHUB_REPOSITORY_OWNER}/${TAG}
          done
